// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://txgnlitdyrnhjqccpljn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR4Z25saXRkeXJuaGpxY2NwbGpuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njg3NDQ0MTUsImV4cCI6MjA4NDMyMDQxNX0.T2sX1HYBxe5mKlF0pbP6Pgwr8d33Z3WUPBxN79nqswQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});